# Generated by Django 5.1.4 on 2025-03-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Agent Referral', 'Agent Referral'), ('Cold Calling', 'Cold Calling'), ('Flyer', 'Flyer'), ('Hot List', 'Hot List'), ('Marketing Day', 'Marketing Day'), ('Newsletter', 'Newsletter'), ('Other', 'Other'), ('Outside Referral', 'Outside Referral'), ('Private Property', 'Private Property'), ('Property 24', 'Property 24'), ('Social Media', 'Social Media'), ('Walk In', 'Walk In'), ('Website', 'Website')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('Follow Up', 'Follow Up'), ('Schedule Valuation', 'Schedule Valuation'), ('Schedule Viewing', 'Schedule Viewing'), ('Valuation Delivered', 'Valuation Delivered'), ('Lead Won', 'Lead Won'), ('Lead Lost', 'Lead Lost')], max_length=50),
        ),
    ]
