# Generated by Django 5.1.4 on 2025-03-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_user_is_agent_user_is_organiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organiser',
            new_name='is_organisor',
        ),
    ]
