# Generated by Django 5.1.4 on 2025-03-18 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
