# Generated by Django 5.1.4 on 2025-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
