# Generated by Django 5.1.4 on 2025-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('Follow Up', 'Follow Up'), ('Schedule Appointment', 'Schedule Appointment'), ('Lead Won', 'Lead Won'), ('Lead Lost', 'Lead Lost')], max_length=50),
        ),
    ]
