# Generated by Django 5.1.7 on 2025-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Agent Referral', 'Agent Referral'), ('Cold Calling', 'Cold Calling'), ('Flyer', 'Flyer'), ('Hot List', 'Hot List'), ('Marketing Day', 'Marketing Day'), ('Newsletter', 'Newsletter'), ('Other', 'Other'), ('Outside Referral', 'Outside Referral'), ('Private Property', 'Private Property'), ('Property 24', 'Property 24'), ('Social Media', 'Social Media'), ('Walk In', 'Walk In'), ('Website', 'Website')], default='Cold Calling', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('Follow Up', 'Follow Up'), ('Schedule Appointment', 'Schedule Appointment'), ('Lead Won', 'Lead Won'), ('Lead Lost', 'Lead Lost')], default='New Lead', max_length=20),
        ),
    ]
