# Generated by Django 5.1.7 on 2025-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_lead_source_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
