# Generated by Django 5.1.4 on 2025-03-20 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_detail'),
        ('leads', '0013_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New Mandate', 'New Mandate'), ('Tenant Application', 'Tenant Application'), ('Tenant Placed', 'Tenant Placed'), ('Managing', 'Managing'), ('Deal Lost', 'Deal Lost'), ('Closed', 'Closed')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Farm', 'Farm'), ('Residential', 'Residential')], max_length=50)),
                ('mandate_type', models.CharField(choices=[('Management', 'Management'), ('Placement', 'Placement'), ('Management and Placement', 'Management and Placement')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_listed', models.DateField(default=django.utils.timezone.now)),
                ('date_rented', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
                ('landlord_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_1', to='clients.client')),
                ('landlord_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_2', to='clients.client')),
                ('tenant_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_1', to='clients.client')),
                ('tenant_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_2', to='clients.client')),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
            },
        ),
    ]
