# Generated by Django 5.1.4 on 2025-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_commission_percentage_rental_management_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_type',
            field=models.CharField(choices=[('Long-Term', 'Long-Term'), ('Short-Term', 'Short-Term'), ('Holiday', 'Holiday')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
