# Generated by Django 5.1.7 on 2025-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='mandate_expiry',
            field=models.DateField(default='2025-03-27'),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_expiry',
            field=models.DateField(default='2025-03-27'),
        ),
    ]
