# Generated by Django 5.1.7 on 2025-03-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_mandate_expiry_rental_rental_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='mandate_expiry',
            field=models.DateField(default='2025/03/27'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_expiry',
            field=models.DateField(default='2025/03/27'),
        ),
    ]
