# Generated by Django 5.1.7 on 2025-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_rental_mandate_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='mandate_expiry',
            field=models.DateField(default='2025/03/28'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_expiry',
            field=models.DateField(default='2025/03/28'),
        ),
    ]
