# Generated by Django 5.1.7 on 2025-04-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_rental_mandate_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='mandate_expiry',
            field=models.DateField(default='2025/04/22'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_expiry',
            field=models.DateField(default='2025/04/22'),
        ),
    ]
