# Generated by Django 5.1.4 on 2025-03-19 15:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0013_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('Agent Referral', 'Agent Referral'), ('Cold Calling', 'Cold Calling'), ('Flyer', 'Flyer'), ('Hot List', 'Hot List'), ('Marketing Day', 'Marketing Day'), ('Newsletter', 'Newsletter'), ('Other', 'Other'), ('Outside Referral', 'Outside Referral'), ('Private Property', 'Private Property'), ('Property 24', 'Property 24'), ('Social Media', 'Social Media'), ('Walk In', 'Walk In'), ('Website', 'Website')], max_length=50)),
                ('role', models.CharField(choices=[('Buyer', 'Buyer'), ('Landlord', 'Landlord'), ('Seller', 'Seller'), ('Tenant', 'Tenant'), ('Potential Buyer', 'Potential Buyer'), ('Potential Landlord', 'Potential Landlord'), ('Potential Seller', 'Potential Seller'), ('Potential Tenant', 'Potential Tenant')], max_length=50)),
                ('contacted', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('follow_up_date', models.DateField(default=datetime.date.today)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
            ],
        ),
    ]
