# Generated by Django 5.1.4 on 2025-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
