# Generated by Django 5.1.7 on 2025-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
