# Generated by Django 4.2 on 2025-03-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0013_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('calls_made', models.IntegerField(blank=True, null=True)),
                ('appointments_set', models.IntegerField(blank=True, null=True)),
                ('listings_secured', models.IntegerField(blank=True, null=True)),
                ('showings_concluded', models.IntegerField(blank=True, null=True)),
                ('deals_closed', models.IntegerField(blank=True, null=True)),
                ('follow_ups', models.IntegerField(blank=True, null=True)),
                ('social_media_posts', models.IntegerField(blank=True, null=True)),
                ('database_growth', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
