# Generated by Django 5.1.4 on 2025-03-19 18:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_detail'),
        ('leads', '0013_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New Mandate', 'New Mandate'), ('Offer', 'Offer'), ('Negotiation', 'Negotiation'), ('Contract', 'Contract'), ('At Transfer', 'At Transfer'), ('Deal Lost', 'Deal Lost'), ('Deal Won', 'Deal Won')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Farm', 'Farm'), ('Residential', 'Residential'), ('Vacant Land', 'Vacant Land')], max_length=50)),
                ('mandate_type', models.CharField(choices=[('Dual', 'Dual'), ('Exclusive Sole', 'Exclusive Sole'), ('Open', 'Open'), ('Sole', 'Sole')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('follow_up_date', models.DateField(default=datetime.date.today)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_listed', models.DateField(default=django.utils.timezone.now)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent')),
                ('buyer_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_1', to='clients.client')),
                ('buyer_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_2', to='clients.client')),
                ('seller_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_1', to='clients.client')),
                ('seller_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_2', to='clients.client')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
