# Generated by Django 5.1.7 on 2025-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='mandate_expiry',
            field=models.DateField(default='2025-03-27'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='mandate_type',
            field=models.CharField(choices=[('Dual / Joint', 'Dual / Joint'), ('Exclusive Sole', 'Exclusive Sole'), ('Open', 'Open'), ('Sole', 'Sole')], max_length=50),
        ),
    ]
