# Generated by Django 5.1.7 on 2025-03-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_mandate_expiry_alter_sale_mandate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mandate_expiry',
            field=models.DateField(default='2025/03/27'),
        ),
    ]
