# Generated by Django 5.1.7 on 2025-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_mandate_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mandate_expiry',
            field=models.DateField(default='28/03/2025'),
        ),
    ]
