# Generated by Django 5.1.7 on 2025-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_mandate_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mandate_expiry',
            field=models.DateField(default='03/04/2025'),
        ),
    ]
