# Generated by Django 5.1.7 on 2025-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_mandate_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mandate_expiry',
            field=models.DateField(default='13/04/2025'),
        ),
    ]
